Repository tgo-mas/SIGApoio, pull requests merged in 2024-08, with the labels that each got.

#97 Reserva repetição
  proj_SIGApoio/app/admin.py
  proj_SIGApoio/app/bo/horarios.py
  proj_SIGApoio/app/forms.py
  proj_SIGApoio/app/migrations/0001_initial.py
  proj_SIGApoio/app/migrations/0002_rename_reserva_reservasemanal_reservadiaunico_and_more.py
  proj_SIGApoio/app/migrations/0002_reservamensal_horafim_reservamensal_horainicio_and_more.py
  proj_SIGApoio/app/migrations/0003_reservadiaunico_descricao_reservamensal_descricao_and_more.py
  proj_SIGApoio/app/migrations/0004_alter_reservadiaunico_diahorainicio.py
  proj_SIGApoio/app/models.py
  proj_SIGApoio/app/templates/reserva/cadastroReservaDia.html
  proj_SIGApoio/app/templates/reserva/cadastroReservaMensal.html
  proj_SIGApoio/app/templates/reserva/tipoReserva.html
  proj_SIGApoio/app/urls.py
  proj_SIGApoio/app/views.py
  proj_SIGApoio/populate.py
  proj_SIGApoio/requirements.txt
Labels: bug, enhancement

#98 Issue 82 - listagem e filtro de reservas #82
  proj_SIGApoio/app/admin.py
  proj_SIGApoio/app/forms.py
  proj_SIGApoio/app/migrations/0001_initial.py
  proj_SIGApoio/app/models.py
  proj_SIGApoio/app/templates/reserva/efetuar_chamado.html
  proj_SIGApoio/app/templates/reserva/filtros_reserva.html
  proj_SIGApoio/app/templates/reserva/lista_filtrada.html
  proj_SIGApoio/app/templates/reserva/listar_reservas.html
  proj_SIGApoio/app/templates/reserva/reserva_details.html
  proj_SIGApoio/app/templatetags/__init__.py
  proj_SIGApoio/app/templatetags/func_utils.py
  proj_SIGApoio/app/urls.py
  proj_SIGApoio/app/views.py
Labels: enhancement

#107 testes de aceitação: TA01, TA02, TA07, TA08 #103
  docs/doc-teste-aceitacao.md
Labels: enhancement

#108 Testes de aceitação Reserva de Local
  docs/doc-teste-aceitacao.md
  docs/doc-userstories.md
  proj_SIGApoio/app/forms.py
Labels: documentation, enhancement

#112 Adição de testes de aceitação para o US01 - Autenticação de usuário #101
  docs/doc-teste-aceitacao.md
  proj_SIGApoio/app/templates/base.html
  proj_SIGApoio/app/templates/local/cad_local.html
  proj_SIGApoio/app/templates/registration/logged_out.html
  proj_SIGApoio/app/templates/registration/login.html
  proj_SIGApoio/app/templates/registration/password_reset_complete.html
  proj_SIGApoio/app/templates/registration/password_reset_confirm.html
  proj_SIGApoio/app/templates/registration/password_reset_done.html
  proj_SIGApoio/app/templates/registration/password_reset_email.html
  proj_SIGApoio/app/templates/registration/password_reset_form.html
  proj_SIGApoio/app/tests/__init__.py
  proj_SIGApoio/app/tests/populate_tests.py
  proj_SIGApoio/app/tests/tests.py
  proj_SIGApoio/app/urls.py
  proj_SIGApoio/app/views.py
  proj_SIGApoio/core/settings.py
  proj_SIGApoio/core/urls.py
  proj_SIGApoio/populate.py
  proj_SIGApoio/populate_horarios.py
Labels: documentation

#111 Adiciona testes de aceitação para o US07 - Manter Empréstimo #105
  docs/doc-teste-aceitacao.md
Labels: documentation, enhancement

#121 Testes reserva #118
  proj_SIGApoio/app/tests/tests.py
  proj_SIGApoio/populate_horarios.py
Labels: enhancement

#122 testes de unidade #117
  proj_SIGApoio/app/tests/tests.py
Labels: enhancement

#123 Implementação dos testes from issue/114
  proj_SIGApoio/app/templates/registration/logged_out.html
  proj_SIGApoio/app/templates/registration/logout.html
  proj_SIGApoio/app/tests/tests.py
  proj_SIGApoio/app/views.py
Labels: enhancement

#136 Implementação da autenticação e permissões de páginas #78
  proj_SIGApoio/app/forms.py
  proj_SIGApoio/app/migrations/0004_user.py
  proj_SIGApoio/app/migrations/0005_remove_user_date_joined.py
  proj_SIGApoio/app/models.py
  proj_SIGApoio/app/templates/registration/login.html
  proj_SIGApoio/app/templates/registration/registration_form.html
  proj_SIGApoio/app/urls.py
  proj_SIGApoio/app/views.py
  proj_SIGApoio/core/roles.py
  proj_SIGApoio/core/settings.py
Labels: enhancement

#138 Reserva final
  proj_SIGApoio/app/bo/horarios.py
  proj_SIGApoio/app/forms.py
  proj_SIGApoio/app/models.py
  proj_SIGApoio/app/templates/base.html
  proj_SIGApoio/app/templates/reserva/editarReservaDia.html
  proj_SIGApoio/app/templates/reserva/editarReservaSemanal.html
  proj_SIGApoio/app/templates/reserva/listar_reservas.html
  proj_SIGApoio/app/templatetags/func_utils.py
  proj_SIGApoio/app/urls.py
  proj_SIGApoio/app/views.py
Labels: bug, enhancement
