Repository tgo-mas/SIGApoio, pull requests merged in 2024-04, with the labels that each got.

#43 Criação da Estrutura de código inicial (projeto django)
  proj_SIGApoio/app_SIGApoio/__init__.py
  proj_SIGApoio/app_SIGApoio/admin.py
  proj_SIGApoio/app_SIGApoio/apps.py
  proj_SIGApoio/app_SIGApoio/migrations/__init__.py
  proj_SIGApoio/app_SIGApoio/models.py
  proj_SIGApoio/app_SIGApoio/templates/usuarios/home.html
  proj_SIGApoio/app_SIGApoio/tests.py
  proj_SIGApoio/app_SIGApoio/views.py
  proj_SIGApoio/manage.py
  proj_SIGApoio/proj_SIGApoio/__init__.py
  proj_SIGApoio/proj_SIGApoio/asgi.py
  proj_SIGApoio/proj_SIGApoio/settings.py
  proj_SIGApoio/proj_SIGApoio/urls.py
  proj_SIGApoio/proj_SIGApoio/wsgi.py
Labels: documentation

#45 Adicionando documento de arquitetura #35
  docs/doc-arquitetura.md
Labels: documentation

#47 Adição dos métodos CRUD nas classes
  docs/diagramadeclasse.md
Labels: documentation

#48 alterações na issue #41
  proj_SIGApoio/app_SIGApoio/admin.py
  proj_SIGApoio/app_SIGApoio/migrations/0001_initial.py
  proj_SIGApoio/app_SIGApoio/migrations/0002_emprestimo.py
  proj_SIGApoio/app_SIGApoio/migrations/0003_delete_emprestimo.py
  proj_SIGApoio/app_SIGApoio/migrations/0004_alter_usuario_tipo.py
  proj_SIGApoio/app_SIGApoio/migrations/0005_emprestimo.py
  proj_SIGApoio/app_SIGApoio/migrations/0006_emprestimo_matusuario_alter_emprestimo_id.py
  proj_SIGApoio/app_SIGApoio/migrations/0007_alter_emprestimo_matusuario.py
  proj_SIGApoio/app_SIGApoio/migrations/0008_alter_emprestimo_matbolsista.py
  proj_SIGApoio/app_SIGApoio/migrations/0009_sala.py
  proj_SIGApoio/app_SIGApoio/migrations/0010_alter_emprestimo_horaentrada_and_more.py
  proj_SIGApoio/app_SIGApoio/migrations/0011_alter_emprestimo_horaentrada.py
  proj_SIGApoio/app_SIGApoio/migrations/0012_alter_emprestimo_horasaida.py
  proj_SIGApoio/app_SIGApoio/migrations/0013_alter_emprestimo_horaentrada.py
  proj_SIGApoio/app_SIGApoio/migrations/0014_alter_emprestimo_horaentrada.py
  proj_SIGApoio/app_SIGApoio/migrations/0015_alter_emprestimo_horasaida.py
  proj_SIGApoio/app_SIGApoio/models.py
  proj_SIGApoio/proj_SIGApoio/urls.py
Labels: enhancement

#49 Alterações de escopo em models.py, diagrama de classe e modelo ER.
  docs/diagramadeclasse.md
  docs/er-model.md
  proj_SIGApoio/Makefile
  proj_SIGApoio/app_SIGApoio/admin.py
  proj_SIGApoio/app_SIGApoio/migrations/0016_emprestimo_ma.py
  proj_SIGApoio/app_SIGApoio/migrations/0017_horario_alter_emprestimo_horaentrada.py
  proj_SIGApoio/app_SIGApoio/migrations/0018_alter_emprestimo_ma.py
  proj_SIGApoio/app_SIGApoio/migrations/0019_horario_dia_alter_emprestimo_ma.py
  proj_SIGApoio/app_SIGApoio/migrations/0020_remove_emprestimo_ma_horario_horafim_and_more.py
  proj_SIGApoio/app_SIGApoio/migrations/0021_alter_horario_dia.py
  proj_SIGApoio/app_SIGApoio/migrations/0022_local_reserva_tipolocal_delete_sala_and_more.py
  proj_SIGApoio/app_SIGApoio/models.py
Labels: documentation, enhancement
