Repository tgo-mas/SIGApoio, pull requests merged in 2024-07, with the labels that each got.

#67 Issue 62
  .gitignore
  README.md
  docs/diagramadeclasse.md
  docs/doc-arquitetura.md
  docs/doc-userstories.md
  docs/doc-visao.md
  docs/er-model.md
  docs/images/reserva_prot.jpg
  docs/images/tela_cadastro_recurso.png
  docs/images/tela_efetuar_chamado.png
  docs/plano-iteracoes.md
  docs/utilizacao-bd.md
  images/cadastro_local.png
  proj_SIGApoio/Makefile
  proj_SIGApoio/app_SIGApoio/__init__.py
  proj_SIGApoio/app_SIGApoio/admin.py
  proj_SIGApoio/app_SIGApoio/apps.py
  proj_SIGApoio/app_SIGApoio/forms.py
  proj_SIGApoio/app_SIGApoio/migrations/0001_initial.py
  proj_SIGApoio/app_SIGApoio/migrations/0002_emprestimo.py
  proj_SIGApoio/app_SIGApoio/migrations/0003_alter_recurso_id_codigo.py
  proj_SIGApoio/app_SIGApoio/migrations/__init__.py
  proj_SIGApoio/app_SIGApoio/models.py
  proj_SIGApoio/app_SIGApoio/static/avatar.webp
  proj_SIGApoio/app_SIGApoio/static/logo.png
  proj_SIGApoio/app_SIGApoio/templates/base.html
  proj_SIGApoio/app_SIGApoio/templates/index.html
  proj_SIGApoio/app_SIGApoio/templates/recurso/cadastro_recurso.html
  proj_SIGApoio/app_SIGApoio/tests.py
  proj_SIGApoio/app_SIGApoio/urls.py
  proj_SIGApoio/app_SIGApoio/views.py
  proj_SIGApoio/manage.py
  proj_SIGApoio/proj_SIGApoio/__init__.py
  proj_SIGApoio/proj_SIGApoio/asgi.py
  proj_SIGApoio/proj_SIGApoio/settings.py
  proj_SIGApoio/proj_SIGApoio/urls.py
  proj_SIGApoio/proj_SIGApoio/wsgi.py
  sonar-project.properties
Labels: enhancement

#69 Adicionado pagina de cadastro de local #64
  proj_SIGApoio/app_SIGApoio/templates/usuarios/cad_page.html
  proj_SIGApoio/app_SIGApoio/templates/usuarios/img/logo.png
  proj_SIGApoio/app_SIGApoio/templates/usuarios/img/profile.png
  proj_SIGApoio/app_SIGApoio/templates/usuarios/styles/cad_page.css
Labels: enhancement

#73 issue #62
  proj_SIGApoio/app_SIGApoio/admin.py
  proj_SIGApoio/app_SIGApoio/forms.py
  proj_SIGApoio/app_SIGApoio/migrations/0001_initial.py
  proj_SIGApoio/app_SIGApoio/migrations/0002_emprestimo.py
  proj_SIGApoio/app_SIGApoio/migrations/0003_delete_emprestimo.py
  proj_SIGApoio/app_SIGApoio/migrations/0004_alter_usuario_tipo.py
  proj_SIGApoio/app_SIGApoio/migrations/0005_emprestimo.py
  proj_SIGApoio/app_SIGApoio/migrations/0006_emprestimo_matusuario_alter_emprestimo_id.py
  proj_SIGApoio/app_SIGApoio/migrations/0007_alter_emprestimo_matusuario.py
  proj_SIGApoio/app_SIGApoio/migrations/0008_alter_emprestimo_matbolsista.py
  proj_SIGApoio/app_SIGApoio/migrations/0009_sala.py
  proj_SIGApoio/app_SIGApoio/migrations/0010_alter_emprestimo_horaentrada_and_more.py
  proj_SIGApoio/app_SIGApoio/migrations/0011_alter_emprestimo_horaentrada.py
  proj_SIGApoio/app_SIGApoio/migrations/0012_alter_emprestimo_horasaida.py
  proj_SIGApoio/app_SIGApoio/migrations/0013_alter_emprestimo_horaentrada.py
  proj_SIGApoio/app_SIGApoio/migrations/0014_alter_emprestimo_horaentrada.py
  proj_SIGApoio/app_SIGApoio/migrations/0015_alter_emprestimo_horasaida.py
  proj_SIGApoio/app_SIGApoio/migrations/0016_emprestimo_ma.py
  proj_SIGApoio/app_SIGApoio/migrations/0017_horario_alter_emprestimo_horaentrada.py
  proj_SIGApoio/app_SIGApoio/migrations/0018_alter_emprestimo_ma.py
  proj_SIGApoio/app_SIGApoio/migrations/0019_horario_dia_alter_emprestimo_ma.py
  proj_SIGApoio/app_SIGApoio/migrations/0020_remove_emprestimo_ma_horario_horafim_and_more.py
  proj_SIGApoio/app_SIGApoio/migrations/0021_alter_horario_dia.py
  proj_SIGApoio/app_SIGApoio/migrations/0022_local_reserva_tipolocal_delete_sala_and_more.py
  proj_SIGApoio/app_SIGApoio/migrations/0023_remove_local_tipo_remove_local_capacidade_and_more.py
  proj_SIGApoio/app_SIGApoio/models.py
  proj_SIGApoio/app_SIGApoio/static/avatar.webp
  proj_SIGApoio/app_SIGApoio/static/logo.png
  proj_SIGApoio/app_SIGApoio/templates/base.html
  proj_SIGApoio/app_SIGApoio/templates/index.html
  proj_SIGApoio/app_SIGApoio/templates/recurso/cadastro_recurso.html
  proj_SIGApoio/app_SIGApoio/templates/usuarios/home.html
  proj_SIGApoio/app_SIGApoio/urls.py
  proj_SIGApoio/app_SIGApoio/views.py
  proj_SIGApoio/proj_SIGApoio/settings.py
  proj_SIGApoio/proj_SIGApoio/urls.py
  sonar-project.properties
Labels: enhancement

#74 Issue #63
  proj_SIGApoio/app_SIGApoio/admin.py
  proj_SIGApoio/app_SIGApoio/forms.py
  proj_SIGApoio/app_SIGApoio/migrations/0004_chamado.py
  proj_SIGApoio/app_SIGApoio/models.py
  proj_SIGApoio/app_SIGApoio/templates/chamado/efetuar_chamado.html
  proj_SIGApoio/app_SIGApoio/templates/index.html
  proj_SIGApoio/app_SIGApoio/urls.py
  proj_SIGApoio/app_SIGApoio/views.py
Labels: enhancement

#83 Cadastro de Reserva
  proj_SIGApoio/app/forms.py
  proj_SIGApoio/app/migrations/0001_initial.py
  proj_SIGApoio/app/migrations/0002_emprestimo_reserva.py
  proj_SIGApoio/app/models.py
  proj_SIGApoio/app/views.py
  proj_SIGApoio/app_SIGApoio/bo/__init__.py
  proj_SIGApoio/app_SIGApoio/bo/horarios.py
  proj_SIGApoio/app_SIGApoio/templates/reserva/cadastroReserva.html
  proj_SIGApoio/app_SIGApoio/templates/reserva/local_option.html
  proj_SIGApoio/core/settings.py
  proj_SIGApoio/core/urls.py
  proj_SIGApoio/populate.py
Labels: enhancement

#84 Correções no merge reserva
  proj_SIGApoio/app/bo/__init__.py
  proj_SIGApoio/app/bo/horarios.py
  proj_SIGApoio/app/forms.py
  proj_SIGApoio/app/migrations/0001_initial.py
  proj_SIGApoio/app/migrations/0002_emprestimo_reserva.py
  proj_SIGApoio/app/templates/reserva/cadastroReserva.html
  proj_SIGApoio/app/templates/reserva/local_option.html
  proj_SIGApoio/core/__init__.py
  proj_SIGApoio/core/settings.py
  proj_SIGApoio/core/urls.py
  proj_SIGApoio/populate.py
Labels: bug, enhancement

#89 Issue 76
  proj_SIGApoio/app/admin.py
  proj_SIGApoio/app/forms.py
  proj_SIGApoio/app/migrations/0001_initial.py
  proj_SIGApoio/app/models.py
  proj_SIGApoio/app/templates/base.html
  proj_SIGApoio/app/templates/chamado/efetuar_chamado.html
  proj_SIGApoio/app/templates/index.html
  proj_SIGApoio/app/tests.py
  proj_SIGApoio/app/urls.py
  proj_SIGApoio/app/views.py
  proj_SIGApoio/core/settings.py
  proj_SIGApoio/core/urls.py
  requirements.txt
  sonar-project.properties
Labels: enhancement

#86 Listar recurso
  proj_SIGApoio/app/templates/recurso/listar_recurso.html
  proj_SIGApoio/app/urls.py
  proj_SIGApoio/app/views.py
  proj_SIGApoio/core/settings.py
Labels: enhancement

#92 Local page
  proj_SIGApoio/app/forms.py
  proj_SIGApoio/app/templates/index.html
  proj_SIGApoio/app/templates/local/cadastro_local.html
  proj_SIGApoio/app/templates/local/listar_local.html
  proj_SIGApoio/app/templates/success_page.html
  proj_SIGApoio/app/urls.py
  proj_SIGApoio/app/views.py
Labels: enhancement

#91 Atualizações no populate.py #88
  proj_SIGApoio/populate.py
Labels: documentation

#96 Listar emprestimos #81
  proj_SIGApoio/app/templates/emprestimos/lista_emprestimos.html
  proj_SIGApoio/app/urls.py
  proj_SIGApoio/app/views.py
Labels: enhancement
